### PR TITLE
F/drunk movements

### LINKED ISSUE #33: Player Drunk Effects
* Change player animation based on drunk meter
* Blur vision of the player as well the more drunk they are

### PR DESCRIPTION
**Pull request by tedgag**
Closes #33 

### Features
- Added new drunk animations and a new player model
- Added player collision with the environment
- Added new player "intoxication" param that increases based on how much they drink
- Reworked the player animation controller to blend between regular animations and drunk animations based on intoxication
- Added jiggle effect on player movement based on intoxication, to simulate tumbling while drunk
- Some small bug fixes

### To test
Play the game and press 'U' a few time to drink beers and get more drunk, then play around with the movements

### CODE REVIEW

**Review by Aleoris — CHANGES_REQUESTED** [review]
1. When you start running from the ground, the player y position start increasing 
2. The player is flickering when moving (rigidbody on the same gameobject as animator)
3. The player can still go through trees and the enclosures

Other than that, love the drunk animation! Super smooth!

**Comment by Zlata-chan** [comment]
Agree with what @Aleoris said! However, I noticed the player's y position increases much faster when intoxication level in animator is set to 0.0 rather than when it's set to 0.1 and above. When it's set to 1, the player doesn't seem to move up y axis at all
The player doesn't seem to go through trees or enclosures anymore but it's still flickering after collision with objects

Awesome animation, love it!!! <3

**Review by Zlata-K — COMMENTED** [review]
Agree with what @Aleoris said! However, I noticed the player's y position increases much faster when intoxication level in animator is set to 0.0 rather than when it's set to 0.1 and above. When it's set to 1, the player doesn't seem to move up y axis at all
The player doesn't seem to go through trees or enclosures anymore but it's still flickering after collision with objects

Awesome animation, love it!!! <3

**Review by Aleoris — APPROVED** [review]
Looks good to me!

**Review by f-michaut — APPROVED** [review]
Looks good to me !

**Pull request merged**
